version: '3.7'

services:
  collection_app: &app
    build:
      context: .
      args:
        requirements: requirements.txt
    command: make docker_run
    container_name: collection_app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - "8585:8585"

  postgres:
    image: postgres:11
    container_name: collection_postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=collection
#    ports:
#        - "54321:5432"

  migrate_and_init:
    <<: *app
    container_name: collection_migrate_and_init
    restart: "no"
    ports: []
    command: make migrate feed_init feed_refresh # <-- uncomment to parse some data
